version: '3.9'

services:
  go-app:
    container_name: go-app
    image: depixen/go-app:1.0.1
    build: .
    environment:
      DATABASE_URL: "host=go_db user=depixen password=depixen-pass dbname=postgres sslmode=disable"
    ports:
      - "8000:8000"
    depends_on:
      - go_db
  go_db:
    container_name: go_db
    image: postgres:12
    environment:
      POSTGRES_PASSWORD: depixen-pass
      POSTGRES_USER: depixen
      POSTGRES_DB: postgres
    ports:
      - "5439:5432"
    volumes:
      - depixen-volume:/var/lib/postgresql/data
volumes:
  depixen-volume: {}